
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

sharedsync:
  websocket:
    endpoint: "/ws-sharedsync"
    allowed-origins:
      - "http://localhost:5173"
      - "http://localhost:3000"

  auth:
    enabled: false

  presence:
    enabled: false


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

redis:
  host: localhost
  port: 6379

debug: false
